### ISSUE TITLE
One server - multiple websites + automatic shutdown

### ISSUE THREAD

**Issue by darksworm** [darksworm/doormouse#5]
I may be hosting multiple websites on the same physical machine, which I want WOL activation for.

Currently the project only supports one hostname/destination per target, so you'd have to create multiple targets - one for each website.

This works alright, except if you also want to use the automatic shutdown feature - then each website would have its own inactivity timer.

Ideally each server would have one shutdown timer, which gets reset on any request going to that server.

We'd probably have to modify the configuration structure to achieve this, for example:

```toml
[[targets]]
name = "service"
# Multiple hostnames and destinations - first hostname points to first destination, etc.
hostnames = ["service.host.com", "alt-service.host.com"]  # The "external" hostnames - what this server receives as Host headers
destinations = ["http://service1.local", "http://service2.local"]  # The actual urls to the servers
health_endpoint = "http://service1.local/ping" # url to check health
# ...
```

or change the concept of target completely with proxies and servers
```toml
[[proxies]]
hostname = "service.host.com" 
destination = "http://service1.local"
server = "server_1"

[[servers]]
name = "server_1"
mac_address = "7c:8b:ad:da:be:51" 
broadcast_ip = "10.0.0.255"
health_endpoint = "http://service2.local/ping"
wol_port = 9 
inactivity_threshold = "1h" 
ssh_host = "service.local:22"
ssh_user = "wol-proxy"
ssh_key_path = "/home/ilmars/.ssh/id_rsa"
shutdown_command = "sudo shutdown -h now"
```

For now I prefer the second option more, as "proxy" and "server" are common terms, whereas "target" is perhaps somewhat unique to this project, so renaming the concepts to what they actually are should lessen the mental load of understanding what's actually going on.
